// Generated by gencpp from file ros_infiniTAM/ros_goalFeedback.msg
// DO NOT EDIT!


#ifndef ROS_INFINITAM_MESSAGE_ROS_GOALFEEDBACK_H
#define ROS_INFINITAM_MESSAGE_ROS_GOALFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_infiniTAM
{
template <class ContainerAllocator>
struct ros_goalFeedback_
{
  typedef ros_goalFeedback_<ContainerAllocator> Type;

  ros_goalFeedback_()
    : completeness(0.0)  {
    }
  ros_goalFeedback_(const ContainerAllocator& _alloc)
    : completeness(0.0)  {
  (void)_alloc;
    }



   typedef float _completeness_type;
  _completeness_type completeness;




  typedef boost::shared_ptr< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ros_goalFeedback_

typedef ::ros_infiniTAM::ros_goalFeedback_<std::allocator<void> > ros_goalFeedback;

typedef boost::shared_ptr< ::ros_infiniTAM::ros_goalFeedback > ros_goalFeedbackPtr;
typedef boost::shared_ptr< ::ros_infiniTAM::ros_goalFeedback const> ros_goalFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_infiniTAM

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/indigo/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/indigo/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/indigo/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/indigo/share/octomap_msgs/cmake/../msg'], 'ros_infiniTAM': ['/home/zeon/catkin_ws/devel/share/ros_infiniTAM/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88ee51b27a1623e0f2cd5fb167ed5f32";
  }

  static const char* value(const ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88ee51b27a1623e0ULL;
  static const uint64_t static_value2 = 0xf2cd5fb167ed5f32ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_infiniTAM/ros_goalFeedback";
  }

  static const char* value(const ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
#feedback definition\n\
float32  completeness\n\
\n\
";
  }

  static const char* value(const ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.completeness);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ros_goalFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_infiniTAM::ros_goalFeedback_<ContainerAllocator>& v)
  {
    s << indent << "completeness: ";
    Printer<float>::stream(s, indent + "  ", v.completeness);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INFINITAM_MESSAGE_ROS_GOALFEEDBACK_H
