// Generated by gencpp from file ros_infiniTAM/ros_goalGoal.msg
// DO NOT EDIT!


#ifndef ROS_INFINITAM_MESSAGE_ROS_GOALGOAL_H
#define ROS_INFINITAM_MESSAGE_ROS_GOALGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_infiniTAM
{
template <class ContainerAllocator>
struct ros_goalGoal_
{
  typedef ros_goalGoal_<ContainerAllocator> Type;

  ros_goalGoal_()
    : position()  {
    }
  ros_goalGoal_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _position_type;
  _position_type position;




  typedef boost::shared_ptr< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ros_goalGoal_

typedef ::ros_infiniTAM::ros_goalGoal_<std::allocator<void> > ros_goalGoal;

typedef boost::shared_ptr< ::ros_infiniTAM::ros_goalGoal > ros_goalGoalPtr;
typedef boost::shared_ptr< ::ros_infiniTAM::ros_goalGoal const> ros_goalGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_infiniTAM

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/indigo/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/indigo/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/indigo/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/indigo/share/octomap_msgs/cmake/../msg'], 'ros_infiniTAM': ['/home/zeon/catkin_ws/devel/share/ros_infiniTAM/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ec164ae840396df197eeb512c1b8515";
  }

  static const char* value(const ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ec164ae840396dfULL;
  static const uint64_t static_value2 = 0x197eeb512c1b8515ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_infiniTAM/ros_goalGoal";
  }

  static const char* value(const ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float32[] position \n\
\n\
";
  }

  static const char* value(const ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ros_goalGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_infiniTAM::ros_goalGoal_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INFINITAM_MESSAGE_ROS_GOALGOAL_H
